name: Cleanup old branches
on:
  push:
    branches:
      - main
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.9
        with:
          repo_token: ${{ github.token }}
          date: '3 months ago'
          dry_run: false
          delete_tags: false
          extra_protected_branch_regex: ^(shields)$
          extra_protected_tag_regex: '^v.*'
          exclude_open_pr_branches: true