name: Run the numdoclint command when a pull request is created or updated.
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  SetGlobalConstants:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      PYTHON_VERSION: 3.11.1
    steps:
      - run: echo 'Setting constans.'
  RunNumdoclint:
    needs: SetGlobalConstants
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CreateCache
        uses: ./.github/actions/create_env_cache
        with:
          python-version: ${{ needs.SetGlobalConstants.outputs.PYTHON_VERSION }}
      - name: Setup the Python dependencies
        uses: ./.github/actions/setup_py_dependencies
        with:
          python-version: ${{ needs.SetGlobalConstants.outputs.PYTHON_VERSION }}
      - name: Set the numdoclint alias
        run: alias numdoclint=/opt/hostedtoolcache/Python/${{ needs.SetGlobalConstants.outputs.PYTHON_VERSION }}/x64/bin/numdoclint
      - name: Run the numdoclint command
        run: python ./scripts/run_numdoclint.py
