name: Secretlint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Lint with Secretlint
        run: npx secretlint "**/*"
